minerals = [
    'Actinolite', 'Adamite', 'Agate', 'Alabaster', 'Albite', 'Alexandrite', 'Allanite', 'Almandine', 'Alunite', 'Amazonite',
    'Amber', 'Amblygonite', 'Amethyst', 'Analcime', 'Anatase', 'Andalusite', 'Andesine', 'Andradite', 'Anglesite', 'Anhydrite',
    'Ankerite', 'Annabergite', 'Anthophyllite', 'Antigorite', 'Apatite', 'Apophyllite', 'Aquamarine', 'Aragonite', 'Argentite', 'Arsenopyrite',
    'Artinite', 'Asbestos', 'Astrophyllite', 'Atacamite', 'Augelite', 'Aurichalcite', 'Azurite', 'Baddeleyite', 'Barite', 'Bastnäsite',
    'Bauxite', 'Benitoite', 'Beryl', 'Biotite', 'Bismuth', 'Bismuthinite', 'Bixbite', 'Bloodstone', 'Boleite', 'Bornite',
    'Borax', 'Bournonite', 'Braunite', 'Brookite', 'Brucite', 'Bustamite', 'Bytownite', 'Calamine', 'Calcite', 'Carnelian',
    'Cassiterite', 'Celestite', 'Cerussite', 'Chabazite', 'Chalcedony', 'Chalcocite', 'Chalcopyrite', 'Charoite', 'Chlorargyrite', 'Chlorite',
    'Chondrodite', 'Chrysoberyl', 'Chrysocolla', 'Chrysoprase', 'Cinnabar', 'Clinochlore', 'Clinoptilolite', 'Cobaltite', 'Colemanite', 'Columbite',
    'Conichalcite', 'Copper', 'Cordierite', 'Covellite', 'Creedite', 'Crocus', 'Crocoite', 'Cryolite', 'Cuprite', 'Danburite',
    'Datolite', 'Diamond', 'Diopside', 'Dioptase', 'Dolomite', 'Dumortierite', 'Elbaite', 'Emerald', 'Enstatite', 'Epidote',
    'Erythrite', 'Euclase', 'Feldspar', 'Fergusonite', 'Ferroaxinite', 'Ferrocolumbite', 'Ferrohornblende', 'Ferromagnesite', 'Fluorapatite', 'Fluorite',
    'Forsterite', 'Fuchsite', 'Galena', 'Garnet', 'Gedrite', 'Germanite', 'Gibbsite', 'Glauberite', 'Goethite', 'Gold',
    'Graphite', 'Greenockite', 'Grossular', 'Gypsum', 'Hackmanite', 'Hauyne', 'Heliodor', 'Hematite', 'Hemimorphite', 'Heulandite',
    'Hiddenite', 'Hornblende', 'Howlite', 'Hureaulite', 'Hypersthene', 'Idocrase', 'Iolite', 'Jade', 'Jadeite', 'Jasper',
    'Jet', 'Kunzite', 'Kyanite', 'Labradorite', 'Lapis Lazuli', 'Lepidolite', 'Limonite', 'Linarite', 'Ludlamite', 'Magnesite',
    'Magnetite', 'Malachite', 'Manganite', 'Marcasite', 'Margarite', 'Meteorite', 'Microcline', 'Millerite', 'Mimetite', 'Minium',
    'Moldavite', 'Molybdenite', 'Morganite', 'Muscovite', 'Natrolite', 'Nepheline', 'Nephrite', 'Obsidian', 'Olivine', 'Onyx',
    'Opal', 'Orpiment', 'Orthoclase', 'Pargasite', 'Pearl', 'Pectolite', 'Peridot', 'Perovskite', 'Petalite', 'Phenakite',
    'Phlogopite', 'Pietersite', 'Prehnite', 'Proustite', 'Pumpellyite', 'Purpurite', 'Pyrite', 'Pyrope', 'Pyrophyllite', 'Pyrrhotite',
    'Quartz', 'Realgar', 'Rhodochrosite', 'Rhodonite', 'Rock Crystal', 'Rose Quartz', 'Ruby', 'Rutile', 'Sapphire', 'Sard',
    'Sardonyx', 'Scheelite', 'Scolecite', 'Selenite', 'Serpentine', 'Sillimanite', 'Silver', 'Smithsonite', 'Sodalite', 'Spessartine',
    'Sphalerite', 'Spinel', 'Staurolite', 'Stibnite', 'Stilbite', 'Sugilite', 'Sulfur', 'Sunstone', 'Talc', 'Tanzanite',
    'Thulite', 'Tigers Eye', 'Topaz', 'Tourmaline', 'Tremolite', 'Trona', 'Tugtupite', 'Turquoise', 'Ulexite', 'Unakite',
    'Uvarovite', 'Vanadinite', 'Variscite', 'Vermiculite', 'Vesuvianite', 'Vivianite', 'Wavellite', 'Wulfenite', 'Xenotime', 'Yttrium',
    'Zincite', 'Zircon'
]
granite = [
    'Quartz', 'Feldspar', 'Plagioclase', 'Orthoclase', 'Biotite', 'Muscovite', 'Amphibole', 'Hornblende', 'Pyroxene',
    'Olivine', 'Garnet', 'Zircon', 'Tourmaline', 'Apatite', 'Titanite', 'Sphene', 'Magnetite', 'Ilmenite', 'Rutile',
    'Beryl', 'Topaz', 'Spinel', 'Molybdenite', 'Cassiterite', 'Wolframite', 'Fluorite', 'Chlorite', 'Kaolinite', 'Montmorillonite',
    'Epidote', 'Zoisite', 'Calcite', 'Serpentine', 'Chalcopyrite', 'Arsenopyrite', 'Pyrite', 'Galena', 'Sphalerite', 'Bismuthinite',
    'Cinnabar', 'Scheelite', 'Stibnite', 'Allanite', 'Monazite', 'Thorite', 'Uraninite', 'Columbite', 'Tantalite', 'Magnetite'
]
metamorphics = [
    'Quartz', 'Feldspar', 'Mica', 'Biotite', 'Muscovite', 'Garnet', 'Staurolite', 'Kyanite', 'Sillimanite', 'Andalusite',
    'Chlorite', 'Talc', 'Hornblende', 'Amphibole', 'Epidote', 'Glaucophane', 'Actinolite', 'Tremolite', 'Serpentine', 'Olivine',
    'Pyroxene', 'Sphene', 'Zoisite', 'Calcite', 'Dolomite', 'Siderite', 'Graphite', 'Chalcopyrite', 'Pyrite', 'Magnetite',
    'Hematite', 'Chromite', 'Gibbsite', 'Beryl', 'Tourmaline', 'Spinel', 'Stibnite', 'Cinnabar', 'Gypsum', 'Anhydrite',
    'Halite', 'Barite', 'Fluorite', 'Azurite', 'Malachite', 'Sphalerite', 'Galena', 'Cassiterite', 'Wolframite', 'Monazite',
    'Zircon', 'Uraninite', 'Rutile', 'Ilmenite', 'Corundum', 'Jadeite', 'Nephrite', 'Jasper', 'Agate', 'Opal'
]
sedimentary = [
    'Quartz', 'Feldspar', 'Clay Minerals', 'Calcite', 'Dolomite', 'Gypsum', 'Halite', 'Siderite', 'Limonite', 'Biotite',
    'Muscovite', 'Kaolinite', 'Montmorillonite', 'Illite', 'Chlorite', 'Sphene', 'Glauconite', 'Apatite', 'Barite', 'Gypsum',
    'Pyrite', 'Hematite', 'Magnetite', 'Chalcopyrite', 'Galena', 'Sphalerite', 'Bauxite', 'Uraninite', 'Cassiterite', 'Corundum',
    'Diamond', 'Jasper', 'Opal', 'Trona', 'Lignite', 'Coal', 'Oil Shale', 'Chert', 'Limestone', 'Diatomite',
    'Sandstone', 'Shale', 'Conglomerate', 'Breccia', 'Evaporites', 'Siltstone', 'Mudstone', 'Dolostone', 'Chalk', 'Marl',
    'Silt', 'Grit', 'Peat', 'Phosphorite', 'Rock Salt', 'Gypsum', 'Lignite', 'Bituminous Coal', 'Anthracite', 'Oil Sands'
]
elements = [
    'Hydrogen', 'Helium', 'Lithium', 'Beryllium', 'Boron', 'Carbon', 'Nitrogen', 'Oxygen', 'Fluorine', 'Neon',
    'Sodium', 'Magnesium', 'Aluminum', 'Silicon', 'Phosphorus', 'Sulfur', 'Chlorine', 'Argon', 'Potassium', 'Calcium',
    'Scandium', 'Titanium', 'Vanadium', 'Chromium', 'Manganese', 'Iron', 'Cobalt', 'Nickel', 'Copper', 'Zinc',
    'Gallium', 'Germanium', 'Arsenic', 'Selenium', 'Bromine', 'Krypton', 'Rubidium', 'Strontium', 'Yttrium', 'Zirconium',
    'Niobium', 'Molybdenum', 'Technetium', 'Ruthenium', 'Rhodium', 'Palladium', 'Silver', 'Cadmium', 'Indium', 'Tin',
    'Antimony', 'Tellurium', 'Iodine', 'Xenon', 'Cesium', 'Barium', 'Lanthanum', 'Cerium', 'Praseodymium', 'Neodymium',
    'Promethium', 'Samarium', 'Europium', 'Gadolinium', 'Terbium', 'Dysprosium', 'Holmium', 'Erbium', 'Thulium', 'Ytterbium',
    'Lutetium', 'Hafnium', 'Tantalum', 'Tungsten', 'Rhenium', 'Osmium', 'Iridium', 'Platinum', 'Gold', 'Mercury',
    'Thallium', 'Lead', 'Bismuth', 'Polonium', 'Astatine', 'Radon', 'Francium', 'Radium', 'Actinium', 'Thorium',
    'Protactinium', 'Uranium', 'Neptunium', 'Plutonium', 'Americium', 'Curium', 'Berkelium', 'Californium', 'Einsteinium', 'Fermium',
    'Mendelevium', 'Nobelium', 'Lawrencium', 'Rutherfordium', 'Dubnium', 'Seaborgium', 'Bohrium', 'Hassium', 'Meitnerium', 'Darmstadtium',
    'Roentgenium', 'Copernicium', 'Nihonium', 'Flerovium', 'Moscovium', 'Livermorium', 'Tennessine', 'Oganesson'
]
element_symbols = {
    'Hydrogen': 'H',
    'Helium': 'He',
    'Lithium': 'Li',
    'Beryllium': 'Be',
    'Boron': 'B',
    'Carbon': 'C',
    'Nitrogen': 'N',
    'Oxygen': 'O',
    'Fluorine': 'F',
    'Neon': 'Ne',
    'Sodium': 'Na',
    'Magnesium': 'Mg',
    'Aluminum': 'Al',
    'Silicon': 'Si',
    'Phosphorus': 'P',
    'Sulfur': 'S',
    'Chlorine': 'Cl',
    'Potassium': 'K',
    'Argon': 'Ar',
    'Calcium': 'Ca',
    'Scandium': 'Sc',
    'Titanium': 'Ti',
    'Vanadium': 'V',
    'Chromium': 'Cr',
    'Manganese': 'Mn',
    'Iron': 'Fe',
    'Cobalt': 'Co',
    'Nickel': 'Ni',
    'Copper': 'Cu',
    'Zinc': 'Zn',
    'Gallium': 'Ga',
    'Germanium': 'Ge',
    'Arsenic': 'As',
    'Selenium': 'Se',
    'Bromine': 'Br',
    'Krypton': 'Kr',
    'Rubidium': 'Rb',
    'Strontium': 'Sr',
    'Yttrium': 'Y',
    'Zirconium': 'Zr',
    'Niobium': 'Nb',
    'Molybdenum': 'Mo',
    'Technetium': 'Tc',
    'Ruthenium': 'Ru',
    'Rhodium': 'Rh',
    'Palladium': 'Pd',
    'Silver': 'Ag',
    'Cadmium': 'Cd',
    'Indium': 'In',
    'Tin': 'Sn',
    'Antimony': 'Sb',
    'Tellurium': 'Te',
    'Iodine': 'I',
    'Xenon': 'Xe',
    'Cesium': 'Cs',
    'Barium': 'Ba',
    'Lanthanum': 'La',
    'Cerium': 'Ce',
    'Praseodymium': 'Pr',
    'Neodymium': 'Nd',
    'Promethium': 'Pm',
    'Samarium': 'Sm',
    'Europium': 'Eu',
    'Gadolinium': 'Gd',
    'Terbium': 'Tb',
    'Dysprosium': 'Dy',
    'Holmium': 'Ho',
    'Erbium': 'Er',
    'Thulium': 'Tm',
    'Ytterbium': 'Yb',
    'Lutetium': 'Lu',
    'Hafnium': 'Hf',
    'Tantalum': 'Ta',
    'Tungsten': 'W',
    'Rhenium': 'Re',
    'Osmium': 'Os',
    'Iridium': 'Ir',
    'Platinum': 'Pt',
    'Gold': 'Au',
    'Mercury': 'Hg',
    'Thallium': 'Tl',
    'Lead': 'Pb',
    'Bismuth': 'Bi',
    'Polonium': 'Po',
    'Astatine': 'At',
    'Radon': 'Rn',
    'Francium': 'Fr',
    'Radium': 'Ra',
    'Actinium': 'Ac',
    'Thorium': 'Th',
    'Protactinium': 'Pa',
    'Uranium': 'U',
    'Neptunium': 'Np',
    'Plutonium': 'Pu',
    'Americium': 'Am',
    'Curium': 'Cm',
    'Berkelium': 'Bk',
    'Californium': 'Cf',
    'Einsteinium': 'Es',
    'Fermium': 'Fm',
    'Mendelevium': 'Md',
    'Nobelium': 'No',
    'Lawrencium': 'Lr',
    'Rutherfordium': 'Rf',
    'Dubnium': 'Db',
    'Seaborgium': 'Sg',
    'Bohrium': 'Bh',
    'Hassium': 'Hs',
    'Meitnerium': 'Mt',
    'Darmstadtium': 'Ds',
    'Roentgenium': 'Rg',
    'Copernicium': 'Cn',
    'Nihonium': 'Nh',
    'Flerovium': 'Fl',
    'Moscovium': 'Mc',
    'Livermorium': 'Lv',
    'Tennessine': 'Ts',
    'Oganesson': 'Og'
}
mineral_compositions = {
    'Quartz': 'SiO2',
    'Feldspar': 'KAlSi3O8',
    'Calcite': 'CaCO3',
    'Muscovite': 'KAl2(AlSi3O10)(OH)2',
    'Biotite': 'K(Fe,Mg)3(AlSi3O10)(OH)2',
    'Garnet': 'X3Y2(SiO4)3',
    'Hematite': 'Fe2O3',
    'Magnetite': 'Fe3O4',
    'Pyrite': 'FeS2',
    'Chalcopyrite': 'CuFeS2'
    'Jet': 'C',
    'Kunzite': 'LiAlSi2O6',
    'Kyanite': 'Al2SiO5',
    'Labradorite': '(Ca,Na)(Al,Si)4O8',
    'Lapis Lazuli': 'Variable composition, primarily Na8(Al6Si6O24)(S,SO)4',
    'Lepidolite': 'K(Li,Al)3(AlSi3O10)(OH,F)2',
    'Limonite': 'FeO(OH)·nH2O',
    'Linarite': 'PbCuSO4(OH)2',
    'Ludlamite': 'Fe2+3(PO4)2·4H2O',
    'Magnesite': 'MgCO3',
    'Magnetite': 'Fe3O4',
    'Malachite': 'Cu2CO3(OH)2',
    'Manganite': 'MnO(OH)',
    'Marcasite': 'FeS2',
    'Margarite': 'CaAl2(Al2Si2O10)(OH)2',
    'Meteorite': 'Variable composition',
    'Microcline': 'K(AlSi3O8)',
    'Millerite': 'NiS',
    'Mimetite': 'Pb5(AsO4)3Cl',
    'Minium': 'Pb3O4',
    'Moldavite': 'Variable composition, primarily SiO2',
    'Molybdenite': 'MoS2',
    'Morganite': 'BeAl2Si6O18',
    'Muscovite': 'KAl2(AlSi3O10)(OH)2',
    'Natrolite': 'Na2Al2Si3O10·2H2O',
    'Nepheline': 'Na3K(Al4Si4O16)',
    'Nephrite': 'Variable composition, primarily Ca2(Mg,Fe)5Si8O22(OH)2',
    'Obsidian': 'Variable composition, primarily SiO2',
    'Olivine': '(Mg,Fe)2SiO4',
    'Onyx': 'Chalcedony with alternating bands of black and white',
    'Opal': 'Variable composition, primarily SiO2·nH2O',
    'Orpiment': 'As2S3',
    'Orthoclase': 'KAlSi3O8',
    'Pargasite': 'NaCa2(Mg4Al)(Si6Al2)O22(OH)2',
    'Pearl': 'Variable composition, primarily CaCO3',
    'Pectolite': 'NaCa2Si3O8(OH)',
    'Peridot': '(Mg,Fe)2SiO4',
    'Perovskite': 'CaTiO3',
    'Petalite': 'LiAlSi4O10',
    'Phenakite': 'Be2SiO4',
    'Phlogopite': 'KMg3AlSi3O10(OH,F)2',
    'Pietersite': 'Variable composition, primarily SiO2',
    'Prehnite': 'Ca2Al(AlSi3O10)(OH)2',
    'Proustite': 'Ag3AsS3',
    'Proustite': 'Ag3AsS3',
    'Pumpellyite': 'Ca2(Mg,Fe)Al2(SiO4)(Si2O7)(OH)2·H2O',
    'Purpurite': 'Mn(PO4)',
    'Pyrite': 'FeS2',
    'Pyrope': 'Mg3Al2(SiO4)3',
    'Pyrophyllite': 'Al2Si4O10(OH)2',
    'Pyrrhotite': 'Fe1-xS',
    'Quartz': 'SiO2',
    'Realgar': 'As4S4',
    'Rhodochrosite': 'MnCO3',
    'Rhodonite': 'MnSiO3',
    'Rock Crystal': 'SiO2',
    'Rose Quartz': 'SiO2',
    'Ruby': 'Al2O3',
    'Rutile': 'TiO2',
    'Sapphire': 'Al2O3',
    'Sard': 'Variety of Chalcedony',
    'Sardonyx': 'Variety of Onyx',
    'Scheelite': 'CaWO4',
    'Scolecite': 'CaAl2Si3O10·3H2O',
    'Selenite': 'CaSO4·2H2O',
    'Serpentine': 'Variable composition, primarily Mg3Si2O5(OH)4',
    'Sillimanite': 'Al2SiO5',
    'Silver': 'Ag',
    'Smithsonite': 'ZnCO3',
    'Sodalite': 'Na8(Al6Si6O24)Cl2',
    'Spessartine': 'Mn3Al2(SiO4)3',
    'Sphalerite': 'ZnS',
    'Spinel': 'Variable composition, primarily MgAl2O4',
    'Staurolite': '(Fe,Mg)2Al9Si4O22(OH)2',
    'Stibnite': 'Sb2S3',
    'Stilbite': 'NaCa2Al5Si13O36·14H2O',
    'Sugilite': 'KNa2(Fe3+,Mn2+,Al)2Li3Si12O30',
    'Sulfur': 'S',
    'Sunstone': 'Variety of Oligoclase',
    'Talc': 'Mg3Si4O10(OH)2',
    'Tanzanite': 'Ca2Al3(SiO4)(Si2O7)O(OH)',
    'Thulite': 'Zoisite with pink color due to Mn',
    'Tigers Eye': 'Variety of Quartz',
    'Topaz': 'Al2SiO4(OH,F)2',
    'Tourmaline': 'Variable composition, primarily (Na,Ca)(Li,Mg,Al)(Al,Fe)6(BO3)3(Si6O18)(OH)4',
    'Tremolite': 'Ca2(Mg5.0-4.5Fe2+0.0-0.5)(Si8O22)(OH)2',
    'Trona': 'Na3(CO3)(HCO3)·2H2O',
    'Tugtupite': 'Na4BeAlSi4O12Cl',
    'Turquoise': 'CuAl6(PO4)4(OH)8·4H2O',
    'Ulexite': 'NaCaB5O6(OH)6·5H2O',
    'Unakite': 'Orthoclase (KAlSi3O8) and Epidote (Ca2(Al,Fe)3(SiO4)3(OH)',
    'Uvarovite': 'Ca3Cr2(SiO4)3',
    'Vanadinite': 'Pb5(VO4)3Cl',
    'Variscite': 'AlPO4·2H2O',
    'Vermiculite': 'Mg0.7(Mg,Fe,Al)6(Si,Al)8O20(OH)4·8H2O',
    'Vesuvianite': '(Ca,Na,☐)19(Al,Mg,Fe3+)13(☐,B,Al,Fe3+)5(Si2O7)4(SiO4)10(OH,F,O)10',
    'Vivianite': 'Fe3(PO4)2·8H2O',
    'Wavellite': 'Al3(PO4)2(OH)3·5H2O',
    'Wulfenite': 'Pb(MoO4)',
    'Xenotime': 'YPO4',
    'Yttrium': 'Y',
    'Zincite': 'ZnO',
    'Zircon': 'ZrSiO4'
}
