Minerals = ['Actinolite',
        'Adamite',
        'Agate',
        'Alabaster',
        'Albite',
        'Alexandrite',
        'Allanite',
        'Almandine',
        'Alunite',
        'Amazonite',
        'Amber',
        'Amblygonite',
        'Amethyst',
        'Analcime',
        'Anatase',
        'Andalusite',
        'Andesine',
        'Andradite',
        'Anglesite',
        'Anhydrite',
        'Ankerite',
        'Annabergite',
        'Anthophyllite',
        'Antigorite',
        'Apatite',
        'Apophyllite',
        'Aquamarine',
        'Aragonite',
        'Argentite',
        'Arsenopyrite',
        'Artinite',
        'Asbestos',
        'Astrophyllite',
        'Atacamite',
        'Augelite',
        'Aurichalcite',
        'Azurite',
        'Baddeleyite',
        'Barite',
        'Bastnäsite',
        'Bauxite',
        'Benitoite',
        'Beryl',
        'Biotite',
        'Bismuth',
        'Bismuthinite',
        'Bixbite',
        'Bloodstone',
        'Boleite',
        'Borax',
        'Bornite',
        'Bournonite',
        'Braunite',
        'Brookite',
        'Brucite',
        'Bustamite',
        'Bytownite',
        'Calamine',
        'Calcite',
        'Carnelian',
        'Cassiterite',
        'Celestite',
        'Cerussite',
        'Chabazite',
        'Chalcedony',
        'Chalcocite',
        'Chalcopyrite',
        'Charoite',
        'Chlorargyrite',
        'Chlorite',
        'Chondrodite',
        'Chrysoberyl',
        'Chrysocolla',
        'Chrysoprase',
        'Cinnabar',
        'Clinochlore',
        'Clinoptilolite',
        'Cobaltite',
        'Colemanite',
        'Columbite',
        'Conichalcite',
        'Copper',
        'Cordierite',
        'Covellite',
        'Creedite',
        'Crocoite',
        'Crocus',
        'Cryolite',
        'Cuprite',
        'Danburite',
        'Datolite',
        'Diamond',
        'Diopside',
        'Dioptase',
        'Dolomite',
        'Dumortierite',
        'Elbaite',
        'Emerald',
        'Enstatite',
        'Epidote',
        'Erythrite',
        'Euclase',
        'Feldspar',
        'Fergusonite',
        'Ferroaxinite',
        'Ferrocolumbite',
        'Ferrohornblende',
        'Ferromagnesite',
        'Fluorapatite',
        'Fluorite',
        'Forsterite',
        'Fuchsite',
        'Galena',
        'Garnet',
        'Gedrite',
        'Germanite',
        'Gibbsite',
        'Glauberite',
        'Goethite',
        'Gold',
        'Graphite',
        'Greenockite',
        'Grossular',
        'Gypsum',
        'Hackmanite',
        'Hauyne',
        'Heliodor',
        'Hematite',
        'Hemimorphite',
        'Heulandite',
        'Hiddenite',
        'Hornblende',
        'Howlite',
        'Hureaulite',
        'Hypersthene',
        'Idocrase',
        'Iolite',
        'Jade',
        'Jadeite',
        'Jasper',
        'Jet',
        'Kunzite',
        'Kyanite',
        'Labradorite',
        'Lapis Lazuli',
        'Lepidolite',
        'Limonite',
        'Linarite',
        'Ludlamite',
        'Magnesite',
        'Magnetite',
        'Malachite',
        'Manganite',
        'Marcasite',
        'Margarite',
        'Meteorite',
        'Microcline',
        'Millerite',
        'Mimetite',
        'Minium',
        'Moldavite',
        'Molybdenite',
        'Morganite',
        'Muscovite',
        'Natrolite',
        'Nepheline',
        'Nephrite',
        'Obsidian',
        'Olivine',
        'Onyx',
        'Opal',
        'Orpiment',
        'Orthoclase',
        'Pargasite',
        'Pearl',
        'Pectolite',
        'Peridot',
        'Perovskite',
        'Petalite',
        'Phenakite',
        'Phlogopite',
        'Pietersite',
        'Prehnite',
        'Proustite',
        'Pumpellyite',
        'Purpurite',
        'Pyrite',
        'Pyrope',
        'Pyrophyllite',
        'Pyrrhotite',
        'Quartz',
        'Realgar',
        'Rhodochrosite',
        'Rhodonite',
        'Rock Crystal',
        'Rose Quartz',
        'Ruby',
        'Rutile',
        'Sapphire',
        'Sard',
        'Sardonyx',
        'Scheelite',
        'Scolecite',
        'Selenite',
        'Serpentine',
        'Sillimanite',
        'Silver',
        'Smithsonite',
        'Sodalite',
        'Spessartine',
        'Sphalerite',
        'Spinel',
        'Staurolite',
        'Stibnite',
        'Stilbite',
        'Sugilite',
        'Sulfur',
        'Sunstone',
        'Talc',
        'Tanzanite',
        'Thulite',
        'Tiger Eye',
        'Tiger Iron',
        'Tigers Eye',
        'Topaz',
        'Tourmaline',
        'Tremolite',
        'Trona',
        'Tsavorite',
        'Tugtupite',
        'Turquoise',
        'Ulexite',
        'Unakite',
        'Uvarovite',
        'Vanadinite',
        'Variscite',
        'Vermiculite',
        'Vesuvianite',
        'Vivianite',
        'Wavellite',
        'Wulfenite',
        'Xenotime',
        'Yttrium',
        'Zincite',
        'Zircon',
        'Zoisite',
    'Abelsonite',
    'Acuminite',
    'Aegirine',
    'Aenigmatite',
    'Aeschynite',
    'Agrellite',
    'Albite-Anorthite Series',
    'Allanite-(Ce)',
    'Allanite-(La)',
    'Allanite-(Y)',
    'Allendeite',
    'Almeidaite',
    'Alumohydrocalcite',
    'Aluminocopiapite',
    'Alunite Group',
    'Alvite',
    'Amakinite',
    'Amblygonite-Montebrasite Series',
    'Amstallite',
    'Anapaite',
    'Anduoite',
    'Andyrobertsite',
    'Angrite Group',
    'Anhydrite Group',
    'Anilite',
    'Antigorite',
    'Apachite',
    'Aplowite',
    'Apuanite',
    'Ardennite',
    'Arfvedsonite',
    'Argentobaumhauerite',
    'Arsenic Group',
    'Arsenolite',
    'Arsenopalladinite',
    'Arsmirandite',
    'Arupite',
    'Asisite',
    'Aspidolite',
    'Astrophyllite',
    'Atelestite',
    'Atencioite',
    'Atokite',
    'Aubertite',
    'Aurostibite',
    'Austinite',
    'Autunite Group',
    'Axinite Group',
    'Babingtonite',
    'Baddeleyite',
    'Baddeleyite-(Y)',
    'Bafertisite',
    'Baileyite',
    'Bairdite',
    'Bakerite',
    'Balipholite',
    'Balmatite',
    'Baratovite',
    'Barberiite',
    'Bario-orthojoaquinite',
    'Barrerite',
    'Barroisite',
    'Barrósite',
    'Barylite',
    'Barysilite',
    'Barytocalcite',
    'Barytolamprophyllite',
    'Bastnäsite-(Ce)',
    'Bastnäsite-(La)',
    'Bastnäsite-(Y)',
    'Bauermannite',
    'Bayldonite Group',
    'Bayleyite',
    'Beaucourtitane',
    'Beaverite-(Cu)',
    'Beckerite',
    'Becquerelite',
    'Bedfordite',
    'Beech Creekite',
    'Begerite',
    'Beidellite',
    'Belaabidiaite',
    'Belovite-(Ce)',
    'Belovite-(La)',
    'Belovite-(Y)',
    'Belyankinite',
    'Bementite',
    'Benauite',
    'Benitoite',
    'Benstonite',
    'Bentorite',
    'Benturite',
    'Beraunite',
    'Bergenite',
    'Berkleyite',
    'Berndtite',
    'Berndtite-(Ce)',
    'Bertrandite',
    'Beryl Group',
    'Berzeliite',
    'Beudantite',
    'Beyerite',
    'Bideauxite',
     'Berzeliite',
    'Beudantite',
    'Beyerite',
    'Bideauxite',
    'Bilibinskite',
    'Bilibinskite-(Ce)',
    'Billietite',
    'Bindheimite',
    'Birnessite',
    'Bischofite',
    'Bischofite-(Ce)',
    'Bismite',
    'Bismoclite',
    'Bismuth',
    'Bismuthinite',
    'Bismutite',
    'Bismutoferrite',
    'Bitikleite',
    'Bituminous-coal',
    'Blödite',
    'Bobdownsite',
    'Bobfergusonite',
    'Bobierrite',
    'Böhmite',
    'Bohrite',
    'Bohdanowiczite',
    'Bokite',
    'Bolivarite',
    'Boltwoodite',
    'Bonaccordite',
    'Bonazziite',
    'Bonattite',
    'Bongardite',
    'Boracite',
    'Borax',
    'Borgite',
    'Bornhardtite',
    'Bornite',
    'Borocookeite',
    'Boromullite',
    'Borosilicate',
    'Boromuscovite',
    'Borovskite',
    'Borshchevskite',
    'Bortnikovite',
    'Boscardinite',
    'Boseite',
    'Bosjemanite',
    'Bosniakite',
    'Botallackite',
    'Botryogen',
    'Boulangerite',
    'Boulangérite',
    'Bournonite',
    'Boussingaultite',
    'Boussingaultite-(Ce)',
    'Boussingaultite-(La)',
    'Boussingaultite-(Y)',
    'Boutwellite',
    'Boutwellite-(Ce)',
    'Bouvetite',
    'Bouzareahite',
    'Böveyite',
    'Bowieite',
    'Bowlesite',
    'Boyleite',
    'Brackebuschite',
    'Brackebuschite-(Ce)',
    'Braitschite',
    'Brannerite',
    'Braunite',
    'Bravoite',
    'Brianyoungite',
    'Brick-red alteration mineral',
    'Bridgmanite',
    'Bridgmanite-(CaFeSiO6)',
    'Bridgmanite-(MgFeSiO6)',
    'Brieyite',
    'Brindleyite',
    'Britholite',
    'Brianyoungite',
    'Brochantite',
    'Brockite',
    'Brogniartite',
    'Bromargyrite',
    'Bromellite',
    'Bromellite-(Mg)',
    'Bromellite-(Mn)',
    'Bromian Chlorargyrite',
    'Bromlite',
    'Broncanite',
    'Bronikowskite',
    'Bronze',
    'Brookite',
    'Browneite',
    'Brownmillerite',
    'Brucite',
    'Brunogeierite',
    'Brüggenite',
 ]
Names = [
    'Actinolite', 'Adamite', 'Agate', 'Alabaster', 'Albite', 'Alexandrite', 'Allanite', 'Almandine', 'Alunite', 'Amazonite',
    'Amber', 'Amblygonite', 'Amethyst', 'Analcime', 'Anatase', 'Andalusite', 'Andesine', 'Andradite', 'Anglesite', 'Anhydrite',
    'Ankerite', 'Annabergite', 'Anthophyllite', 'Antigorite', 'Apatite', 'Apophyllite', 'Aquamarine', 'Aragonite', 'Argentite', 'Arsenopyrite',
    'Artinite', 'Asbestos', 'Astrophyllite', 'Atacamite', 'Augelite', 'Aurichalcite', 'Azurite', 'Baddeleyite', 'Barite', 'Bastnäsite',
    'Bauxite', 'Benitoite', 'Beryl', 'Biotite', 'Bismuth', 'Bismuthinite', 'Bixbite', 'Bloodstone', 'Boleite', 'Bornite',
    'Borax', 'Bournonite', 'Braunite', 'Brookite', 'Brucite', 'Bustamite', 'Bytownite', 'Calamine', 'Calcite', 'Carnelian',
    'Cassiterite', 'Celestite', 'Cerussite', 'Chabazite', 'Chalcedony', 'Chalcocite', 'Chalcopyrite', 'Charoite', 'Chlorargyrite', 'Chlorite',
    'Chondrodite', 'Chrysoberyl', 'Chrysocolla', 'Chrysoprase', 'Cinnabar', 'Clinochlore', 'Clinoptilolite', 'Cobaltite', 'Colemanite', 'Columbite',
    'Conichalcite', 'Copper', 'Cordierite', 'Covellite', 'Creedite', 'Crocus', 'Crocoite', 'Cryolite', 'Cuprite', 'Danburite',
    'Datolite', 'Diamond', 'Diopside', 'Dioptase', 'Dolomite', 'Dumortierite', 'Elbaite', 'Emerald', 'Enstatite', 'Epidote',
    'Erythrite', 'Euclase', 'Feldspar', 'Fergusonite', 'Ferroaxinite', 'Ferrocolumbite', 'Ferrohornblende', 'Ferromagnesite', 'Fluorapatite', 'Fluorite',
    'Forsterite', 'Fuchsite', 'Galena', 'Garnet', 'Gedrite', 'Germanite', 'Gibbsite', 'Glauberite', 'Goethite', 'Gold',
    'Graphite', 'Greenockite', 'Grossular', 'Gypsum', 'Hackmanite', 'Hauyne', 'Heliodor', 'Hematite', 'Hemimorphite', 'Heulandite',
    'Hiddenite', 'Hornblende', 'Howlite', 'Hureaulite', 'Hypersthene', 'Idocrase', 'Iolite', 'Jade', 'Jadeite', 'Jasper',
    'Jet', 'Kunzite', 'Kyanite', 'Labradorite', 'Lapis Lazuli', 'Lepidolite', 'Limonite', 'Linarite', 'Ludlamite', 'Magnesite',
    'Magnetite', 'Malachite', 'Manganite', 'Marcasite', 'Margarite', 'Meteorite', 'Microcline', 'Millerite', 'Mimetite', 'Minium',
    'Moldavite', 'Molybdenite', 'Morganite', 'Muscovite', 'Natrolite', 'Nepheline', 'Nephrite', 'Obsidian', 'Olivine', 'Onyx',
    'Opal', 'Orpiment', 'Orthoclase', 'Pargasite', 'Pearl', 'Pectolite', 'Peridot', 'Perovskite', 'Petalite', 'Phenakite',
    'Phlogopite', 'Pietersite', 'Prehnite', 'Proustite', 'Pumpellyite', 'Purpurite', 'Pyrite', 'Pyrope', 'Pyrophyllite', 'Pyrrhotite',
    'Quartz', 'Realgar', 'Rhodochrosite', 'Rhodonite', 'Rock Crystal', 'Rose Quartz', 'Ruby', 'Rutile', 'Sapphire', 'Sard',
    'Sardonyx', 'Scheelite', 'Scolecite', 'Selenite', 'Serpentine', 'Sillimanite', 'Silver', 'Smithsonite', 'Sodalite', 'Spessartine',
    'Sphalerite', 'Spinel', 'Staurolite', 'Stibnite', 'Stilbite', 'Sugilite', 'Sulfur', 'Sunstone', 'Talc', 'Tanzanite',
    'Thulite', 'Tigers Eye', 'Topaz', 'Tourmaline', 'Tremolite', 'Trona', 'Tugtupite', 'Turquoise', 'Ulexite', 'Unakite',
    'Uvarovite', 'Vanadinite', 'Variscite', 'Vermiculite', 'Vesuvianite', 'Vivianite', 'Wavellite', 'Wulfenite', 'Xenotime', 'Yttrium',
    'Zincite', 'Zircon', 'Actinolite', 'Adamite', 'Agate', 'Alabaster', 'Albite', 'Alexandrite', 'Allanite',
    'Almandine', 'Alunite', 'Amazonite', 'Amber', 'Amblygonite', 'Amethyst', 'Analcime',
    'Anatase', 'Andalusite', 'Andesine', 'Andradite', 'Anglesite', 'Anhydrite', 'Ankerite',
    'Annabergite', 'Anthophyllite', 'Antigorite', 'Apatite', 'Apophyllite', 'Aquamarine',
    'Aragonite', 'Argentite', 'Arsenopyrite', 'Artinite', 'Asbestos', 'Astrophyllite',
    'Atacamite', 'Augelite', 'Aurichalcite', 'Azurite', 'Baddeleyite', 'Barite', 'Bastnäsite',
    'Bauxite', 'Benitoite', 'Beryl', 'Biotite', 'Bismuth', 'Bismuthinite', 'Bixbite',
    'Bloodstone', 'Boleite', 'Borax', 'Bornite', 'Bournonite', 'Braunite', 'Brookite',
    'Brucite', 'Bustamite', 'Bytownite', 'Calamine', 'Calcite', 'Carnelian', 'Cassiterite',
    'Celestite', 'Cerussite', 'Chabazite', 'Chalcedony', 'Chalcocite', 'Chalcopyrite',
    'Charoite', 'Chlorargyrite', 'Chlorite', 'Chondrodite', 'Chrysoberyl', 'Chrysocolla',
    'Chrysoprase', 'Cinnabar', 'Clinochlore', 'Clinoptilolite', 'Cobaltite', 'Colemanite',
    'Columbite', 'Conichalcite', 'Copper', 'Cordierite', 'Covellite', 'Creedite', 'Crocoite',
    'Crocus', 'Cryolite', 'Cuprite', 'Danburite', 'Datolite', 'Diamond', 'Diopside',
    'Dioptase', 'Dolomite', 'Dumortierite', 'Elbaite', 'Emerald', 'Enstatite', 'Epidote',
    'Erythrite', 'Euclase', 'Feldspar', 'Fergusonite', 'Ferroaxinite', 'Ferrocolumbite',
    'Ferrohornblende', 'Ferromagnesite', 'Fluorapatite', 'Fluorite', 'Forsterite', 'Fuchsite',
    'Galena', 'Garnet', 'Gedrite', 'Germanite', 'Gibbsite', 'Glauberite', 'Goethite', 'Gold',
    'Graphite', 'Greenockite', 'Grossular', 'Gypsum', 'Hackmanite', 'Hauyne', 'Heliodor',
    'Hematite', 'Hemimorphite', 'Heulandite', 'Hiddenite', 'Hornblende', 'Howlite', 'Hureaulite',
    'Hypersthene', 'Idocrase', 'Iolite','Jadeite', 'Jasper', 'Jet', 'Kunzite', 'Kyanite', 'Labradorite', 'Lapis Lazuli',
    'Lepidolite', 'Limonite', 'Linarite', 'Ludlamite', 'Magnesite', 'Magnetite',
    'Malachite', 'Manganite', 'Marcasite', 'Margarite', 'Meteorite', 'Microcline',
    'Millerite', 'Mimetite', 'Minium', 'Moldavite', 'Molybdenite', 'Morganite',
    'Muscovite', 'Natrolite', 'Nepheline', 'Nephrite', 'Obsidian', 'Olivine', 'Onyx',
    'Opal', 'Orpiment', 'Orthoclase', 'Pargasite', 'Pearl', 'Pectolite', 'Peridot',
    'Perovskite', 'Petalite', 'Phenakite', 'Phlogopite', 'Pietersite', 'Prehnite',
    'Proustite', 'Pumpellyite', 'Purpurite', 'Pyrite', 'Pyrope', 'Pyrophyllite',
    'Pyrrhotite', 'Quartz', 'Realgar', 'Rhodochrosite', 'Rhodonite', 'Rock Crystal',
    'Rose Quartz', 'Ruby', 'Rutile', 'Sapphire', 'Sard', 'Sardonyx', 'Scheelite',
    'Scolecite', 'Selenite', 'Serpentine', 'Sillimanite', 'Silver', 'Smithsonite',
    'Sodalite', 'Spessartine', 'Sphalerite', 'Spinel', 'Staurolite', 'Stibnite',
    'Stilbite', 'Sugilite', 'Sulfur', 'Sunstone', 'Talc', 'Tanzanite', 'Thulite',
    'Tiger Eye', 'Tiger Iron', 'Tigers Eye', 'Topaz', 'Tourmaline', 'Tremolite',
    'Trona', 'Tsavorite', 'Tugtupite', 'Turquoise', 'Ulexite', 'Unakite', 'Uvarovite',
    'Vanadinite', 'Variscite', 'Vermiculite', 'Vesuvianite', 'Vivianite', 'Wavellite',
    'Wulfenite', 'Xenotime', 'Yttrium', 'Zincite', 'Zircon', 'Zoisite'
]
Granites = [
    'Quartz', 'Feldspar', 'Plagioclase', 'Orthoclase', 'Biotite', 'Muscovite', 'Amphibole', 'Hornblende', 'Pyroxene',
    'Olivine', 'Garnet', 'Zircon', 'Tourmaline', 'Apatite', 'Titanite', 'Sphene', 'Magnetite', 'Ilmenite', 'Rutile',
    'Beryl', 'Topaz', 'Spinel', 'Molybdenite', 'Cassiterite', 'Wolframite', 'Fluorite', 'Chlorite', 'Kaolinite', 'Montmorillonite',
    'Epidote', 'Zoisite', 'Calcite', 'Serpentine', 'Chalcopyrite', 'Arsenopyrite', 'Pyrite', 'Galena', 'Sphalerite', 'Bismuthinite',
    'Cinnabar', 'Scheelite', 'Stibnite', 'Allanite', 'Monazite', 'Thorite', 'Uraninite', 'Columbite', 'Tantalite', 'Magnetite'
]
Metamorphics = [
    'Quartz', 'Feldspar', 'Mica', 'Biotite', 'Muscovite', 'Garnet', 'Staurolite', 'Kyanite', 'Sillimanite', 'Andalusite',
    'Chlorite', 'Talc', 'Hornblende', 'Amphibole', 'Epidote', 'Glaucophane', 'Actinolite', 'Tremolite', 'Serpentine', 'Olivine',
    'Pyroxene', 'Sphene', 'Zoisite', 'Calcite', 'Dolomite', 'Siderite', 'Graphite', 'Chalcopyrite', 'Pyrite', 'Magnetite',
    'Hematite', 'Chromite', 'Gibbsite', 'Beryl', 'Tourmaline', 'Spinel', 'Stibnite', 'Cinnabar', 'Gypsum', 'Anhydrite',
    'Halite', 'Barite', 'Fluorite', 'Azurite', 'Malachite', 'Sphalerite', 'Galena', 'Cassiterite', 'Wolframite', 'Monazite',
    'Zircon', 'Uraninite', 'Rutile', 'Ilmenite', 'Corundum', 'Jadeite', 'Nephrite', 'Jasper', 'Agate', 'Opal'
]
Sedimentary = [
    'Quartz', 'Feldspar', 'Clay Minerals', 'Calcite', 'Dolomite', 'Gypsum', 'Halite', 'Siderite', 'Limonite', 'Biotite',
    'Muscovite', 'Kaolinite', 'Montmorillonite', 'Illite', 'Chlorite', 'Sphene', 'Glauconite', 'Apatite', 'Barite', 'Gypsum',
    'Pyrite', 'Hematite', 'Magnetite', 'Chalcopyrite', 'Galena', 'Sphalerite', 'Bauxite', 'Uraninite', 'Cassiterite', 'Corundum',
    'Diamond', 'Jasper', 'Opal', 'Trona', 'Lignite', 'Coal', 'Oil Shale', 'Chert', 'Limestone', 'Diatomite',
    'Sandstone', 'Shale', 'Conglomerate', 'Breccia', 'Evaporites', 'Siltstone', 'Mudstone', 'Dolostone', 'Chalk', 'Marl',
    'Silt', 'Grit', 'Peat', 'Phosphorite', 'Rock Salt', 'Gypsum', 'Lignite', 'Bituminous Coal', 'Anthracite', 'Oil Sands'
]

Compositions = {
    'Quartz': 'SiO2',
    'Feldspar': 'KAlSi3O8',
    'Calcite': 'CaCO3',
    'Muscovite': 'KAl2(AlSi3O10)(OH)2',
    'Biotite': 'K(Fe,Mg)3(AlSi3O10)(OH)2',
    'Garnet': 'X3Y2(SiO4)3',
    'Hematite': 'Fe2O3',
    'Magnetite': 'Fe3O4',
    'Pyrite': 'FeS2',
    'Chalcopyrite': 'CuFeS2',
    'Jet': 'C',
    'Kunzite': 'LiAlSi2O6',
    'Kyanite': 'Al2SiO5',
    'Labradorite': '(Ca,Na)(Al,Si)4O8',
    'Lapis Lazuli': 'Variable composition, primarily Na8(Al6Si6O24)(S,SO)4',
    'Lepidolite': 'K(Li,Al)3(AlSi3O10)(OH,F)2',
    'Limonite': 'FeO(OH)·nH2O',
    'Linarite': 'PbCuSO4(OH)2',
    'Ludlamite': 'Fe2+3(PO4)2·4H2O',
    'Magnesite': 'MgCO3',
    'Magnetite': 'Fe3O4',
    'Malachite': 'Cu2CO3(OH)2',
    'Manganite': 'MnO(OH)',
    'Marcasite': 'FeS2',
    'Margarite': 'CaAl2(Al2Si2O10)(OH)2',
    'Meteorite': 'Variable composition',
    'Microcline': 'K(AlSi3O8)',
    'Millerite': 'NiS',
    'Mimetite': 'Pb5(AsO4)3Cl',
    'Minium': 'Pb3O4',
    'Moldavite': 'Variable composition, primarily SiO2',
    'Molybdenite': 'MoS2',
    'Morganite': 'BeAl2Si6O18',
    'Muscovite': 'KAl2(AlSi3O10)(OH)2',
    'Natrolite': 'Na2Al2Si3O10·2H2O',
    'Nepheline': 'Na3K(Al4Si4O16)',
    'Nephrite': 'Variable composition, primarily Ca2(Mg,Fe)5Si8O22(OH)2',
    'Obsidian': 'Variable composition, primarily SiO2',
    'Olivine': '(Mg,Fe)2SiO4',
    'Onyx': 'Chalcedony with alternating bands of black and white',
    'Opal': 'Variable composition, primarily SiO2·nH2O',
    'Orpiment': 'As2S3',
    'Orthoclase': 'KAlSi3O8',
    'Pargasite': 'NaCa2(Mg4Al)(Si6Al2)O22(OH)2',
    'Pearl': 'Variable composition, primarily CaCO3',
    'Pectolite': 'NaCa2Si3O8(OH)',
    'Peridot': '(Mg,Fe)2SiO4',
    'Perovskite': 'CaTiO3',
    'Petalite': 'LiAlSi4O10',
    'Phenakite': 'Be2SiO4',
    'Phlogopite': 'KMg3AlSi3O10(OH,F)2',
    'Pietersite': 'Variable composition, primarily SiO2',
    'Prehnite': 'Ca2Al(AlSi3O10)(OH)2',
    'Proustite': 'Ag3AsS3',
    'Proustite': 'Ag3AsS3',
    'Pumpellyite': 'Ca2(Mg,Fe)Al2(SiO4)(Si2O7)(OH)2·H2O',
    'Purpurite': 'Mn(PO4)',
    'Pyrite': 'FeS2',
    'Pyrope': 'Mg3Al2(SiO4)3',
    'Pyrophyllite': 'Al2Si4O10(OH)2',
    'Pyrrhotite': 'Fe1-xS',
    'Quartz': 'SiO2',
    'Realgar': 'As4S4',
    'Rhodochrosite': 'MnCO3',
    'Rhodonite': 'MnSiO3',
    'Rock Crystal': 'SiO2',
    'Rose Quartz': 'SiO2',
    'Ruby': 'Al2O3',
    'Rutile': 'TiO2',
    'Sapphire': 'Al2O3',
    'Sard': 'Variety of Chalcedony',
    'Sardonyx': 'Variety of Onyx',
    'Scheelite': 'CaWO4',
    'Scolecite': 'CaAl2Si3O10·3H2O',
    'Selenite': 'CaSO4·2H2O',
    'Serpentine': 'Variable composition, primarily Mg3Si2O5(OH)4',
    'Sillimanite': 'Al2SiO5',
    'Silver': 'Ag',
    'Smithsonite': 'ZnCO3',
    'Sodalite': 'Na8(Al6Si6O24)Cl2',
    'Spessartine': 'Mn3Al2(SiO4)3',
    'Sphalerite': 'ZnS',
    'Spinel': 'Variable composition, primarily MgAl2O4',
    'Staurolite': '(Fe,Mg)2Al9Si4O22(OH)2',
    'Stibnite': 'Sb2S3',
    'Stilbite': 'NaCa2Al5Si13O36·14H2O',
    'Sugilite': 'KNa2(Fe3+,Mn2+,Al)2Li3Si12O30',
    'Sulfur': 'S',
    'Sunstone': 'Variety of Oligoclase',
    'Talc': 'Mg3Si4O10(OH)2',
    'Tanzanite': 'Ca2Al3(SiO4)(Si2O7)O(OH)',
    'Thulite': 'Zoisite with pink color due to Mn',
    'Tigers Eye': 'Variety of Quartz',
    'Topaz': 'Al2SiO4(OH,F)2',
    'Tourmaline': 'Variable composition, primarily (Na,Ca)(Li,Mg,Al)(Al,Fe)6(BO3)3(Si6O18)(OH)4',
    'Tremolite': 'Ca2(Mg5.0-4.5Fe2+0.0-0.5)(Si8O22)(OH)2',
    'Trona': 'Na3(CO3)(HCO3)·2H2O',
    'Tugtupite': 'Na4BeAlSi4O12Cl',
    'Turquoise': 'CuAl6(PO4)4(OH)8·4H2O',
    'Ulexite': 'NaCaB5O6(OH)6·5H2O',
    'Unakite': 'Orthoclase (KAlSi3O8) and Epidote (Ca2(Al,Fe)3(SiO4)3(OH)',
    'Uvarovite': 'Ca3Cr2(SiO4)3',
    'Vanadinite': 'Pb5(VO4)3Cl',
    'Variscite': 'AlPO4·2H2O',
    'Vermiculite': 'Mg0.7(Mg,Fe,Al)6(Si,Al)8O20(OH)4·8H2O',
    'Vesuvianite': '(Ca,Na,☐)19(Al,Mg,Fe3+)13(☐,B,Al,Fe3+)5(Si2O7)4(SiO4)10(OH,F,O)10',
    'Vivianite': 'Fe3(PO4)2·8H2O',
    'Wavellite': 'Al3(PO4)2(OH)3·5H2O',
    'Wulfenite': 'Pb(MoO4)',
    'Xenotime': 'YPO4',
    'Yttrium': 'Y',
    'Zincite': 'ZnO',
    'Zircon': 'ZrSiO4'
}
mineral_compositions = {
    'Jet': {'C': 85, 'H': 10, 'O': 1, 'S': 4},
    'Kunzite': {'Li': 3, 'Al': 4, 'Si': 12, 'O': 30, 'H': 2},
    'Kyanite': {'Al': 2, 'Si': 2, 'O': 9},
    'Labradorite': {'Na': 5, 'Ca': 30, 'Al': 4, 'Si': 28, 'O': 63},
    'Lapis Lazuli': {'Na': 8, 'Ca': 1, 'Fe': 1, 'S': 4, 'Al': 8, 'Si': 32, 'O': 72},
    'Lepidolite': {'K': 2, 'Li': 1, 'Al': 3, 'Si': 8, 'O': 20, 'H': 2},
    'Limonite': {'Fe': 3, 'O': 4, 'H': 4},
    'Linarite': {'Pb': 1, 'Cu': 1, 'S': 4, 'O': 10},
    'Ludlamite': {'Mn': 1, 'Fe': 1, 'P': 4, 'O': 12, 'H': 8},
    'Magnesite': {'Mg': 1, 'C': 1, 'O': 3},
    'Magnetite': {'Fe': 3, 'O': 4},
    'Malachite': {'Cu': 2, 'C': 1, 'O': 4, 'H': 2},
    'Manganite': {'Mn': 1, 'O': 2, 'H': 2},
    'Marcasite': {'Fe': 1, 'S': 2},
    'Margarite': {'Na': 4, 'Ca': 1, 'Al': 2, 'Si': 8, 'O': 20, 'H': 2},
    'Meteorite': {'Fe': 18, 'Ni': 2},
    'Microcline': {'K': 1, 'Al': 1, 'Si': 3, 'O': 8},
    'Millerite': {'Ni': 1, 'S': 2},
    'Mimetite': {'Pb': 1, 'As': 1, 'O': 4, 'Cl': 1},
    'Minium': {'Pb': 1, 'O': 4},
    'Moldavite': {'Si': 1, 'O': 2, 'Al': 1},
    'Molybdenite': {'Mo': 1, 'S': 2},
    'Morganite': {'Be': 1, 'Al': 2, 'Si': 6, 'O': 18, 'H': 4},
    'Muscovite': {'K': 2, 'Al': 3, 'Si': 12, 'O': 30, 'H': 2},
    'Natrolite': {'Na': 2, 'Al': 4, 'Si': 12, 'O': 36, 'H': 18},
    'Nepheline': {'Na': 1, 'Al': 1, 'Si': 1, 'O': 4},
    'Nephrite': {'Ca': 1, 'Mg': 3, 'Fe': 1, 'Si': 4, 'O': 11, 'H': 2},
    'Obsidian': {'Si': 1, 'O': 2},
    'Olivine': {'Mg': 2, 'Fe': 2, 'Si': 4, 'O': 12},
    'Onyx': {'Si': 1, 'O': 2},
    'Opal': {'Si': 1, 'O': 2, 'H': 2},
    'Orpiment': {'As': 2, 'S': 3},
    'Orthoclase': {'K': 1, 'Al': 1, 'Si': 3, 'O': 8},
    'Pargasite': {'Na': 2, 'Ca': 1, 'Mg': 3, 'Al': 2, 'Si': 6, 'O': 22, 'H': 2},
    'Pearl': {'Ca': 1, 'C': 1, 'O': 3, 'H': 2},
    'Pectolite': {'Na': 1, 'Ca': 1, 'Al': 2, 'Si': 3, 'O': 10, 'H': 2},
    'Peridot': {'Mg': 2, 'Fe': 2, 'Si': 4, 'O': 12},
    'Perovskite': {'Ca': 1, 'Ti': 1, 'O': 3},
    'Petalite': {'Li': 1, 'Al': 1, 'Si': 4, 'O': 10},
    'Phenakite': {'Be': 1, 'Si': 1, 'O': 4},
    'Phlogopite': {'K': 3, 'Mg': 3, 'Al': 1, 'Si': 3, 'O': 10, 'H': 2},
    'Pietersite': {'Si': 4, 'O': 12},
    'Prehnite': {'Ca': 2, 'Al': 1, 'Si': 3, 'O': 10, 'H': 2},
    'Proustite': {'Ag': 3, 'As': 1, 'S': 3},
    'Pumpellyite': {'Ca': 2, 'Al': 3, 'Si': 12, 'O': 36, 'H': 6},
    'Purpurite': {'Mn': 1, 'P': 1, 'O': 4, 'H': 4},
    'Pyrite': {'Fe': 1, 'S': 2},
    'Pyrope': {'Mg': 3, 'Al': 2, 'Si': 3, 'O': 12},
    'Pyrophyllite': {'Al': 2, 'Si': 4, 'O': 10, 'H': 2},
    'Pyrrhotite': {'Fe': 1, 'S': 1},
    'Quartz': {'Si': 1, 'O': 2},
    'Realgar': {'As': 4, 'S': 4},
    'Rhodochrosite': {'Mn': 1, 'C': 1, 'O': 3},
    'Rhodonite': {'Mn': 1, 'Si': 1, 'O': 3},
    'Rock Crystal': {'Si': 1, 'O': 2},
    'Rose Quartz': {'Si': 1, 'O': 2},
    'Ruby': {'Al': 2, 'O': 3},
    'Rutile': {'Ti': 1, 'O': 2},
    'Sapphire': {'Al': 2, 'O': 3},
    'Sard': {'Si': 1, 'O': 2},
    'Sardonyx': {'Si': 1, 'O': 2},
    'Scheelite': {'Ca': 1, 'W': 1, 'O': 4},
    'Scolecite': {'Ca': 1, 'Al': 2, 'Si': 3, 'O': 10, 'H': 2},
    'Selenite': {'Ca': 1, 'S': 1, 'O': 4, 'H': 2},
    'Serpentine': {'Mg': 3, 'Si': 2, 'O': 5, 'H': 4},
    'Sillimanite': {'Al': 2, 'Si': 1, 'O': 5},
    'Silver': {'Ag': 1},
    'Smithsonite': {'Zn': 1, 'C': 1, 'O': 3},
    'Sodalite': {'Na': 8, 'Al': 6, 'Si': 6, 'O': 24, 'Cl': 2},
    'Spessartine': {'Mn': 3, 'Al': 2, 'Si': 3, 'O': 12},
    'Sphalerite': {'Zn': 1, 'S': 1},
    'Spinel': {'Mg': 1, 'Al': 2, 'O': 4},
    'Staurolite': {'Fe': 2, 'Al': 2, 'Si': 4, 'O': 12},
    'Stibnite': {'Sb': 2, 'S': 3},
    'Stilbite': {'Na': 6, 'Ca': 2, 'Al': 8, 'Si': 24, 'O': 72, 'H': 24},
    'Sugilite': {'K': 1, 'Na': 1, 'Fe': 1, 'Mn': 2, 'Si': 12, 'O': 30, 'H': 4},
    'Sulfur': {'S': 1},
    'Sunstone': {'Na': 1, 'Ca': 1, 'Al': 1, 'Si': 3, 'O': 8},
    'Talc': {'Mg': 3, 'Si': 4, 'O': 12, 'H': 2},
    'Tanzanite': {'Ca': 1, 'Al': 1, 'Si': 3, 'O': 12},
    'Thulite': {'Ca': 1, 'Mn': 2, 'Si': 2, 'O': 7},
    'Tiger Eye': {'Si': 1, 'O': 2},
    'Tiger Iron': {'Fe': 3, 'O': 4},
    'Topaz': {'Al': 2, 'Si': 1, 'O': 4, 'F': 8, 'H': 2},
    'Tourmaline': {'Na': 3, 'Al': 6, 'B': 3, 'Si': 6, 'O': 27, 'H': 3},
    'Tremolite': {'Ca': 2, 'Mg': 5, 'Si': 8, 'O': 22, 'H': 2},
    'Trona': {'Na': 3, 'C': 1, 'O': 4, 'H': 2},
    'Tsavorite': {'Ca': 3, 'Al': 2, 'Si': 3, 'O': 12},
    'Tugtupite': {'Na': 4, 'Be': 1, 'Al': 1, 'Si': 4, 'O': 12, 'Cl': 1},
    'Turquoise': {'Cu': 1, 'Al': 6, 'P': 4, 'O': 17, 'H': 2},
    'Ulexite': {'Na': 2, 'Ca': 1, 'B': 5, 'O': 9, 'H': 2},
    'Unakite': {'K': 1, 'Na': 1, 'Al': 1, 'Si': 3, 'O': 8},
    'Uvarovite': {'Ca': 3, 'Cr': 2, 'Si': 3, 'O': 12},
    'Vanadinite': {'Pb': 1, 'Cl': 1, 'V': 1, 'O': 4},
    'Variscite': {'Al': 1, 'P': 1, 'O': 4, 'H': 4},
    'Vesuvianite': {'Ca': 19, 'Al': 4, 'Mg': 4, 'Si': 12, 'O': 45, 'H': 2},
    'Vivianite': {'Fe': 3, 'P': 2, 'O': 8, 'H': 8},
    'Wulfenite': {'Pb': 1, 'Mo': 1, 'O': 4},
    'Zincite': {'Zn': 1, 'O': 2},
    'Zircon': {'Zr': 1, 'Si': 1, 'O': 4},
    'Zoisite': {'Ca': 2, 'Al': 3, 'Si': 3, 'O': 13, 'H': 2}
}

from pprint import pprint
def filter_minerals():    
    names = []
    lists = [Minerals, Names, mineral_compositions.keys()]
    for l in lists:
        for name in l:
            names.append(name)
    names = sorted(list(set(names)))
    pprint(names)

filter_minerals()